import { AggregatorData } from "../types";

export function createEmptyAggregatorDraft(): AggregatorData {
  return {
    id: null,
    userId: null,
    name: "",
    number: "",
    state: "",
    district: "",
    taluk: "",
    village: "",
    buyerType: null,
    cropName: null,
    experience: null,
    capacity: null,
    capacityUnit: null,
    tAndC: null,
    nextAction: null,
    nextActionDueDate: null,
    interestTo: null,
    readyToSupply: null,
    tag: null,
    confidence: null,
    lastInteracted: null,
    interestedCompanies: "",
    interestsCompaniesIds: [],
    feVisited: null,
    hasStock: null,
    currentStock: null,
    currentStockUnit: null,
    notes: null,
    radius: null,
    accurateRadius: null,
    otherCrops: [],
    isVisited: false,
    isInterestedToWork: null,
    frequency: null,
    upfrontPaymentNeedPercentage: null,
interestedToWorkPercentage: null,
    __raw: null,
    __rawUserFromLookup: null,
    updatedAt: null,
  };
}

